name: MERN CD Pipeline

on:
  push:
    branches: [main]

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # backend
      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:backend ./backend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:backend

      # frontend
      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:frontend ./frontend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:frontend

      # ai-agent service
      - name: Build AI Agent image
        run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:ai-agent ./ai_agent

      - name: Push ai-agent image
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:ai-agent

  deploy-backend:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Deploy Backend to Render
        run: curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Deploy Frontend to Render
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}

  deploy-ai-agent:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Deploy AI Agent Service
        run: curl -X POST ${{ secrets.AI_AGENT_URL }}
    