name: MERN CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "22.17.1"

jobs:
  backend:
    name: Backend CI for build, test, lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      mongodb:
        image: mongo:6
        ports: 
          - 27017:27017

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with: 
          node-version: '22.17.1' 
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install dependenciess
        run: npm ci

      - name: Run Lint
        run: npm run lint --if--present

      - name: Run Test
        env:
          MONGO_URI: mongodb://localhost:27017/mern_app_ci
        run: npm test

      - name: Security Audit (fail on high)
        run: npm audit --audit-level=high

      - name: Build
        run: npm run build --if--present

      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend build
          path: |
            backend/dist
            backend/build
            backend/package*.json

  frontend:
    name: Frontend CI Pipeline for build, lint, test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.17.1' 
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint --if-present

      - name: Run Build
        run: npm run build

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend build
          path: |
            frontend/build
            frontend/dist
            frontend/package*.json

  